/**
 * The historian's work list for one edition: everything that still blocks compilation after
 * `normalize.ts --partial`, in one Markdown page.
 *
 *   node tools/normalize/pending.ts --edition <edition_id> [--data <root>] [--out <dir>]
 *
 * Writes <out>/pending-<edition_id>.md (default build/reports/) with, per table of the edition's
 * notation file:
 *  1. illegible or unresolved keyed cells with no waiver, with the resolver's note and the
 *     citation a waivers.csv row would use (cells printed once but keyed in two overlapping crops
 *     are listed once, with both crops);
 *  2. columns the normaliser left out, with the reason;
 *  3. running_rules.csv rows not yet reviewed, with the note as printed, the proposal and the
 *     services that use it;
 *  4. trains of tables without train numbers whose times match a numbered train of another table
 *     at a shared station (candidates for one train_key; V04 compares only equal keys);
 *  5. the notation file's open questions (_draft.uncertain_for_historian).
 * Reads only; deterministic (no dates, sorted lists).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { ROOT } from '../make/paths.ts';
import { loadDataset, type Dataset } from '../schema/dataset.ts';
import { formatCitation } from '../schema/citation.ts';
import { cmpStr } from '../schema/csv.ts';
import { stopsByService } from '../schema/derive.ts';
import { inputFromDataset, normalizeTable } from './normalize.ts';

const REF: Record<string, (col: number, row: number) => string> = {
  cell: (c, r) => `c${c}r${r}`, header: (c, r) => `h${r}c${c}`, label: (c, r) => `l${c}r${r}`, footnote: (_c, r) => `f${r}`,
};
const esc = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const tableOrder = (a: string, b: string) => (Number(a) - Number(b)) || cmpStr(a, b);

export function pendingReport(ds: Dataset, editionId: string): string {
  const ed = ds.t.editions.find((e) => e.edition_id === editionId);
  const notation = ds.notations.get(editionId);
  if (!ed || !notation) return `# Pending work: ${editionId}\n\nEdition or notation file not found.\n`;
  const tables = Object.keys(notation.tables).sort(tableOrder);
  const out: string[] = [`# Pending work for the historian: ${editionId}`, '',
    `${ed.label} (${ed.source_id}). Generated by \`node tools/normalize/pending.ts --edition ${editionId}\` from the resolved keying, the canonical tables and the notation file; nothing here is compiled until it is settled.`, ''];
  const sbs = stopsByService(ds);
  const summary: string[] = ['| Table | Services | Stops | Columns left out | Illegible cells (keyed) |', '|---|---|---|---|---|'];
  const sections: string[] = [];
  let totalCells = 0;
  for (const t of tables) {
    const inp = inputFromDataset(ds, editionId, t);
    if ('error' in inp) { sections.push(`## Table ${t}`, '', `Not normalised: ${inp.error}`, ''); continue; }
    const res = normalizeTable(inp, { partial: true });
    // 1. Unreadable cells.
    const cellsOut = new Map<string, { kind: string; ref: string; text: string; notes: string[]; crops: string[]; cite: string; page: number }>();
    for (const c of inp.crops) {
      for (const r of inp.cells.get(c.crop_id) ?? []) {
        if (r.resolution !== '' && r.resolution !== 'illegible') continue;
        const ref = REF[r.kind]!(r.col, r.row);
        const cite = formatCitation({ source: ed.source_id, pageSeq: c.page_seq, tableRef: t, crop: c.crop_id, cell: ref });
        if (ds.t.waivers.some((w) => w.src === cite)) continue;
        totalCells++;
        const key = r.kind === 'footnote' ? `${c.crop_id}:${ref}` : `${r.kind}:${ref}`;
        const prev = cellsOut.get(key);
        if (prev) { prev.crops.push(c.crop_id); if (r.note && !prev.notes.includes(r.note)) prev.notes.push(r.note); continue; }
        cellsOut.set(key, { kind: r.kind, ref, text: r.text_as_printed, notes: r.note ? [r.note] : [], crops: [c.crop_id], cite, page: c.page_seq });
      }
    }
    const own = ds.t.services.filter((s) => s.edition_id === editionId && s.table_ref === t);
    const nStops = own.reduce((n, s) => n + (sbs.get(s.service_id)?.length ?? 0), 0);
    const skippedCols = [...new Map(res.skipped.map((s) => [s.col, s])).values()].sort((a, b) => a.col - b.col);
    const keyed = [...cellsOut.values()].reduce((n, c) => n + c.crops.length, 0);
    summary.push(`| ${t} | ${own.length} | ${nStops} | ${skippedCols.length} | ${keyed} (${cellsOut.size} printed) |`);
    sections.push(`## Table ${t}`, '');
    sections.push(`### Illegible or unresolved cells (${keyed} keyed, ${cellsOut.size} printed)`, '');
    if (cellsOut.size === 0) sections.push('None.', '');
    else {
      sections.push('| Cell | Kind | Read as | Resolver\'s note | Crops | Waiver src |', '|---|---|---|---|---|---|');
      const order = (x: { kind: string; ref: string; crops: string[] }) => `${x.kind}:${x.crops[0]}:${x.ref}`;
      for (const c of [...cellsOut.values()].sort((a, b) => cmpStr(order(a), order(b)))) {
        sections.push(`| ${c.ref} (p${c.page}) | ${c.kind} | ${esc(c.text) || '—'} | ${esc(c.notes.join(' / ')) || '—'} | ${c.crops.join(', ')} | \`${c.cite}\` |`);
      }
      sections.push('');
    }
    sections.push(`### Columns left out by the normaliser (${skippedCols.length})`, '');
    if (skippedCols.length === 0) sections.push('None.', '');
    else for (const s of skippedCols) sections.push(`- c${s.col}: ${esc(s.error)}`);
    if (skippedCols.length) sections.push('');
    const warns = res.issues.filter((i) => i.level === 'warning' && !i.message.startsWith('pending:'));
    if (warns.length) {
      sections.push('### Normaliser remarks', '');
      for (const w of warns) sections.push(`- ${esc(w.where.replace(`${editionId} ${t} `, ''))}: ${esc(w.message)}`);
      sections.push('');
    }
  }
  // 3. Unreviewed running rules.
  const fn = new Map(ds.t.footnotes.map((f) => [`${f.edition_id}\u0000${f.table_ref}\u0000${f.mark}`, f]));
  const rules = ds.t.running_rules.filter((r) => r.edition_id === editionId && !r.reviewed_by)
    .sort((a, b) => tableOrder(a.table_ref, b.table_ref) || cmpStr(a.mark, b.mark));
  const rr: string[] = [`## Running rules awaiting review (${rules.length})`, '',
    'Each row is a proposal in `data/canonical/running_rules.csv` (reviewed_by empty). The normaliser applies it in --partial mode; V07 blocks every service that uses it until a historian fills reviewed_by.', ''];
  if (rules.length) {
    rr.push('| Table | Mark | Note as printed | Proposal | Interpreted by | Services |', '|---|---|---|---|---|---|');
    for (const r of rules) {
      const users = ds.t.services.filter((s) => s.edition_id === editionId && s.table_ref === r.table_ref && s.running_as_printed.split(';').includes(r.mark)).map((s) => s.service_id.slice(editionId.length + 1)).sort(cmpStr);
      rr.push(`| ${r.table_ref} | \`${esc(r.mark)}\` | ${esc(fn.get(`${r.edition_id}\u0000${r.table_ref}\u0000${r.mark}`)?.text_as_printed ?? '(not in footnotes.csv)')} | \`${esc(r.rule_dsl)}\` | ${esc(r.interpreted_by)} | ${users.join(', ') || '—'} |`);
    }
    rr.push('');
  }
  // 4. Same-train candidates across tables (unnumbered trains).
  const svcs = ds.t.services.filter((s) => s.edition_id === editionId);
  const cand: string[] = [];
  for (const a of svcs) {
    if (a.train_no_as_printed) continue;
    const sa = sbs.get(a.service_id) ?? [];
    for (const b of svcs) {
      if (!b.train_no_as_printed || b.table_ref === a.table_ref) continue;
      const sb = sbs.get(b.service_id) ?? [];
      const same = sa.filter((x) => sb.some((y) => y.station_id === x.station_id && ((x.dep_local && x.dep_local === y.dep_local) || (x.arr_local && x.arr_local === y.arr_local))));
      if (same.length) cand.push(`| ${a.service_id.slice(editionId.length + 1)} | ${b.service_id.slice(editionId.length + 1)} (${b.train_no_as_printed}) | ${same.map((x) => x.station_id).join(', ')} |`);
    }
  }
  const cc: string[] = [`## Same-train candidates (${cand.length})`, '',
    'Trains of tables that print no numbers whose time at a shared station equals that of a numbered train in another table. Giving them one train_key would let V04 compare them; that is the historian\'s call.', ''];
  if (cand.length) cc.push('| Unnumbered | Numbered | Equal at |', '|---|---|---|', ...[...new Set(cand)].sort(cmpStr), '');
  // 5. Open questions of the notation file.
  const nt = ds.raw.notationTexts.get(ed.notation_file);
  let open: string[] = [];
  try { const j = JSON.parse(nt ?? '{}') as { _draft?: { uncertain_for_historian?: unknown } }; if (Array.isArray(j._draft?.uncertain_for_historian)) open = j._draft.uncertain_for_historian.map(String); } catch { open = []; }
  const oq = [`## Open questions in ${ed.notation_file} (${open.length})`, '', ...open.map((q) => `- ${esc(q)}`), ''];
  out.push('## Summary', '', ...summary, '', `Illegible or unresolved keyed cells without a waiver: ${totalCells}.`, '');
  out.push(...rr, ...oq, ...cc, ...sections);
  return `${out.join('\n').replace(/\n+$/, '')}\n`;
}

function argValue(args: string[], name: string): string | undefined {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const edition = argValue(args, '--edition');
  if (!edition) { console.error('usage: node tools/normalize/pending.ts --edition <edition_id> [--data <root>] [--out <dir>]'); process.exit(2); }
  const data = resolve(argValue(args, '--data') ?? join(ROOT, 'data'));
  const outDir = resolve(argValue(args, '--out') ?? join(ROOT, 'build', 'reports'));
  const md = pendingReport(loadDataset(data), edition);
  mkdirSync(outDir, { recursive: true });
  const file = join(outDir, `pending-${edition}.md`);
  writeFileSync(file, md);
  console.log(`pending work for ${edition}: ${file}`);
}
