/* Generated by tools/compile/test/compile.test.ts (UPDATE_GOLDEN=1). Do not edit. */
import type { ReadyBundle } from '#kit/data/bundle.ts';

export const SYN_C07_BUNDLE = {
  "calendar": [
    {
      "cite": 2,
      "day": 5322,
      "effects": [
        "SYN_P003"
      ],
      "id": "SYN_EV2",
      "jurisdiction": "SYN_J_PRU",
      "kind": "secret-order",
      "timeLocal": null,
      "title": "SYN watch list activated",
      "zone": null
    },
    {
      "cite": 2,
      "day": 5325,
      "effects": [
        "SYN_P002"
      ],
      "id": "SYN_EV1",
      "jurisdiction": "SYN_J_RU",
      "kind": "decree",
      "timeLocal": 68400,
      "title": "SYN frontier closed",
      "zone": "SYN_Z_SPB_CIV"
    }
  ],
  "citations": [
    {
      "edition": null,
      "pageSeq": 5,
      "printedPage": "xv",
      "source": "SYN_SRC_H",
      "sourceTitle": "SYN Handbook for Travellers",
      "tableRef": null
    },
    {
      "edition": null,
      "pageSeq": 6,
      "printedPage": "12",
      "source": "SYN_SRC_H",
      "sourceTitle": "SYN Handbook for Travellers",
      "tableRef": null
    },
    {
      "edition": null,
      "pageSeq": 8,
      "printedPage": "14",
      "source": "SYN_SRC_H",
      "sourceTitle": "SYN Handbook for Travellers",
      "tableRef": null
    },
    {
      "edition": null,
      "pageSeq": 9,
      "printedPage": "15",
      "source": "SYN_SRC_H",
      "sourceTitle": "SYN Handbook for Travellers",
      "tableRef": null
    },
    {
      "edition": "SYN_E1",
      "pageSeq": 10,
      "printedPage": "10",
      "source": "SYN_SRC_S",
      "sourceTitle": "SYN Continental Guide, June 1914",
      "tableRef": "SYN_T1"
    },
    {
      "edition": "SYN_E1",
      "pageSeq": 11,
      "printedPage": "11",
      "source": "SYN_SRC_S",
      "sourceTitle": "SYN Continental Guide, June 1914",
      "tableRef": "SYN_T2"
    },
    {
      "edition": "SYN_E1",
      "pageSeq": 12,
      "printedPage": "12",
      "source": "SYN_SRC_S",
      "sourceTitle": "SYN Continental Guide, June 1914",
      "tableRef": "SYN_T3"
    },
    {
      "edition": "SYN_E1",
      "pageSeq": 13,
      "printedPage": "13",
      "source": "SYN_SRC_S",
      "sourceTitle": "SYN Continental Guide, June 1914",
      "tableRef": "SYN_T1U"
    },
    {
      "edition": "SYN_E1",
      "pageSeq": 14,
      "printedPage": "14",
      "source": "SYN_SRC_S",
      "sourceTitle": "SYN Continental Guide, June 1914",
      "tableRef": "SYN_T2U"
    },
    {
      "edition": "SYN_E1",
      "pageSeq": 15,
      "printedPage": "15",
      "source": "SYN_SRC_S",
      "sourceTitle": "SYN Continental Guide, June 1914",
      "tableRef": "SYN_T3U"
    },
    {
      "edition": "SYN_E2",
      "pageSeq": 20,
      "printedPage": "20",
      "source": "SYN_SRC_W",
      "sourceTitle": "SYN Continental Guide, December 1913",
      "tableRef": "SYN_T1"
    },
    {
      "edition": "SYN_E2",
      "pageSeq": 21,
      "printedPage": "21",
      "source": "SYN_SRC_W",
      "sourceTitle": "SYN Continental Guide, December 1913",
      "tableRef": "SYN_T1U"
    }
  ],
  "cities": [
    {
      "civilZone": "SYN_Z_MEZ_CIV",
      "country": "DE",
      "id": "SYN_C_BER",
      "jurisdiction": "SYN_J_PRU",
      "name": "SYN Berlin"
    },
    {
      "civilZone": "SYN_Z_GMT_CIV",
      "country": "GB",
      "id": "SYN_C_DOV",
      "jurisdiction": "SYN_J_GB",
      "name": "SYN Dover"
    },
    {
      "civilZone": "SYN_Z_MEZ_CIV",
      "country": "DE",
      "id": "SYN_C_EYD",
      "jurisdiction": "SYN_J_PRU",
      "name": "SYN Eydtkuhnen"
    },
    {
      "civilZone": "SYN_Z_GMT_CIV",
      "country": "GB",
      "id": "SYN_C_LON",
      "jurisdiction": "SYN_J_GB",
      "name": "SYN London"
    },
    {
      "civilZone": "SYN_Z_GMT_CIV",
      "country": "BE",
      "id": "SYN_C_OST",
      "jurisdiction": "SYN_J_BE",
      "name": "SYN Ostend"
    },
    {
      "civilZone": "SYN_Z_SPB_CIV",
      "country": "RU",
      "id": "SYN_C_SPB",
      "jurisdiction": "SYN_J_RU",
      "name": "SYN St Petersburg"
    },
    {
      "civilZone": "SYN_Z_SPB_CIV",
      "country": "RU",
      "id": "SYN_C_WIR",
      "jurisdiction": "SYN_J_RU",
      "name": "SYN Wirballen"
    }
  ],
  "designValues": [
    {
      "id": "DV-001",
      "rationale": "Synthetic. No printed minimum change at the pier.",
      "unit": "minutes",
      "value": 20
    },
    {
      "id": "DV-002",
      "rationale": "Synthetic. Lag between registration and the slip reaching the police.",
      "unit": "hours",
      "value": 24
    },
    {
      "id": "DV-003",
      "rationale": "Synthetic. Chosen for the test network, continued on a second line.",
      "unit": "minutes",
      "value": 15
    }
  ],
  "editions": [
    {
      "family": "SYN_F1",
      "id": "SYN_E1",
      "issueDay": 5233,
      "label": "SYN Continental Guide June 1914",
      "source": "SYN_SRC_S",
      "validFrom": 5233,
      "validTo": 5385
    },
    {
      "family": "SYN_F1",
      "id": "SYN_E2",
      "issueDay": 5021,
      "label": "SYN Continental Guide December 1913",
      "source": "SYN_SRC_W",
      "validFrom": 5021,
      "validTo": 5232
    }
  ],
  "fares": [
    {
      "amountMinor": 5260,
      "cite": 5,
      "cls": "1",
      "currency": "DEM",
      "edition": "SYN_E1",
      "from": "SYN_BER",
      "ret": false,
      "scope": "table",
      "to": "SYN_EYD",
      "validityDays": null
    },
    {
      "amountMinor": 3420,
      "cite": 5,
      "cls": "2",
      "currency": "DEM",
      "edition": "SYN_E1",
      "from": "SYN_BER",
      "ret": false,
      "scope": "table",
      "to": "SYN_EYD",
      "validityDays": null
    },
    {
      "amountMinor": 384,
      "cite": 4,
      "cls": "boat",
      "currency": "GBP",
      "edition": "SYN_E1",
      "from": "SYN_DOV",
      "ret": false,
      "scope": "table",
      "to": "SYN_OST",
      "validityDays": null
    },
    {
      "amountMinor": 1152,
      "cite": 4,
      "cls": "1",
      "currency": "GBP",
      "edition": "SYN_E1",
      "from": "SYN_LON",
      "ret": true,
      "scope": "table",
      "to": "SYN_DOV",
      "validityDays": 30
    },
    {
      "amountMinor": 672,
      "cite": 4,
      "cls": "1",
      "currency": "GBP",
      "edition": "SYN_E1",
      "from": "SYN_LON",
      "ret": false,
      "scope": "table",
      "to": "SYN_DOV",
      "validityDays": null
    },
    {
      "amountMinor": 480,
      "cite": 4,
      "cls": "2",
      "currency": "GBP",
      "edition": "SYN_E1",
      "from": "SYN_LON",
      "ret": false,
      "scope": "table",
      "to": "SYN_DOV",
      "validityDays": null
    },
    {
      "amountMinor": 288,
      "cite": 4,
      "cls": "3",
      "currency": "GBP",
      "edition": "SYN_E1",
      "from": "SYN_LON",
      "ret": false,
      "scope": "table",
      "to": "SYN_DOV",
      "validityDays": null
    },
    {
      "amountMinor": 7680,
      "cite": 5,
      "cls": "1",
      "currency": "GBP",
      "edition": "SYN_E1",
      "from": "SYN_LON",
      "ret": false,
      "scope": "through",
      "to": "SYN_SPB",
      "validityDays": null
    },
    {
      "amountMinor": 9850,
      "cite": 5,
      "cls": "1",
      "currency": "BEF",
      "edition": "SYN_E1",
      "from": "SYN_OST",
      "ret": false,
      "scope": "table",
      "to": "SYN_BER",
      "validityDays": null
    },
    {
      "amountMinor": 6420,
      "cite": 5,
      "cls": "2",
      "currency": "BEF",
      "edition": "SYN_E1",
      "from": "SYN_OST",
      "ret": false,
      "scope": "table",
      "to": "SYN_BER",
      "validityDays": null
    },
    {
      "amountMinor": 672,
      "cite": 10,
      "cls": "1",
      "currency": "GBP",
      "edition": "SYN_E2",
      "from": "SYN_LON",
      "ret": false,
      "scope": "table",
      "to": "SYN_DOV",
      "validityDays": null
    }
  ],
  "institutions": [
    {
      "basis": "historical",
      "cite": 3,
      "city": "SYN_C_LON",
      "from": 0,
      "id": "SYN_I_BANK",
      "jurisdiction": "SYN_J_GB",
      "kind": "bank",
      "name": "SYN Commercial Bank",
      "nameAsPeriod": "SYN Commercial Bank Ltd",
      "parent": null,
      "readsKinds": [],
      "to": null
    },
    {
      "basis": "historical",
      "cite": 1,
      "city": "SYN_C_BER",
      "from": 0,
      "id": "SYN_I_POL",
      "jurisdiction": "SYN_J_PRU",
      "kind": "police",
      "name": "SYN Political Police",
      "nameAsPeriod": "SYN Politische Polizei",
      "parent": null,
      "readsKinds": [
        "registration.slip",
        "frontier.record"
      ],
      "to": null
    }
  ],
  "meta": {
    "dataHash": "766e44183798f2e5",
    "freezeTag": "syn-data-v1",
    "game": "syn-c07",
    "schema": 1,
    "status": "ready",
    "synthetic": true,
    "window": [
      5222,
      5355
    ]
  },
  "minChange": [
    {
      "basis": "design",
      "dv": "DV-003",
      "minSec": 900,
      "station": "SYN_BER"
    },
    {
      "basis": "design",
      "dv": "DV-001",
      "minSec": 1200,
      "station": "SYN_DOV"
    },
    {
      "basis": "historical",
      "cite": 6,
      "minSec": 1800,
      "station": "SYN_WIR"
    }
  ],
  "params": [
    {
      "cite": 2,
      "dateBasis": "historical",
      "from": 5325,
      "id": "SYN_P002",
      "key": "SYN_EYD>SYN_WIR",
      "keyKind": "edge",
      "param": "frontier_closed",
      "public": true,
      "tier": 0,
      "to": null,
      "value": true,
      "valueBasis": "historical"
    },
    {
      "cite": 2,
      "dateBasis": "historical",
      "from": 5322,
      "id": "SYN_P003",
      "key": "SYN_I_POL",
      "keyKind": "institution",
      "param": "watch_list_active",
      "public": false,
      "tier": 0,
      "to": null,
      "value": true,
      "valueBasis": "historical"
    },
    {
      "cite": 3,
      "dateBasis": "historical",
      "dv": "DV-002",
      "from": 4748,
      "id": "SYN_P004",
      "key": "SYN_J_PRU",
      "keyKind": "jurisdiction",
      "param": "registration_lag_hours",
      "public": false,
      "tier": 2,
      "to": null,
      "value": 24,
      "valueBasis": "design"
    },
    {
      "cite": 3,
      "dateBasis": "historical",
      "from": 4748,
      "id": "SYN_P005",
      "key": "SYN_I_BANK",
      "keyKind": "institution",
      "param": "bank_hours",
      "public": true,
      "tier": 1,
      "to": 5478,
      "value": {
        "close": "15:00",
        "open": "09:00"
      },
      "valueBasis": "historical"
    }
  ],
  "stationZones": [
    {
      "cite": 0,
      "from": -2466,
      "station": "SYN_BER",
      "to": null,
      "zone": "SYN_Z_MEZ"
    },
    {
      "cite": 0,
      "from": -3652,
      "station": "SYN_DOV",
      "to": null,
      "zone": "SYN_Z_GMT"
    },
    {
      "cite": 0,
      "from": -2466,
      "station": "SYN_EYD",
      "to": null,
      "zone": "SYN_Z_MEZ"
    },
    {
      "cite": 0,
      "from": -3652,
      "station": "SYN_LON",
      "to": null,
      "zone": "SYN_Z_GMT"
    },
    {
      "cite": 0,
      "from": -2801,
      "station": "SYN_OST",
      "to": null,
      "zone": "SYN_Z_GMT"
    },
    {
      "cite": 0,
      "from": -3652,
      "station": "SYN_SPB",
      "to": null,
      "zone": "SYN_Z_SPB"
    },
    {
      "cite": 0,
      "from": -3652,
      "station": "SYN_WIR",
      "to": null,
      "zone": "SYN_Z_SPB"
    }
  ],
  "stations": [
    {
      "city": "SYN_C_BER",
      "country": "DE",
      "frontier": false,
      "frontierPair": null,
      "id": "SYN_BER",
      "name": "SYN Berlin Friedrichstrasse"
    },
    {
      "city": "SYN_C_DOV",
      "country": "GB",
      "frontier": false,
      "frontierPair": null,
      "id": "SYN_DOV",
      "name": "SYN Dover Pier"
    },
    {
      "city": "SYN_C_EYD",
      "country": "DE",
      "frontier": true,
      "frontierPair": "SYN_WIR",
      "id": "SYN_EYD",
      "name": "SYN Eydtkuhnen"
    },
    {
      "city": "SYN_C_LON",
      "country": "GB",
      "frontier": false,
      "frontierPair": null,
      "id": "SYN_LON",
      "name": "SYN London Victoria"
    },
    {
      "city": "SYN_C_OST",
      "country": "BE",
      "frontier": false,
      "frontierPair": null,
      "id": "SYN_OST",
      "name": "SYN Ostend Quay"
    },
    {
      "city": "SYN_C_SPB",
      "country": "RU",
      "frontier": false,
      "frontierPair": null,
      "id": "SYN_SPB",
      "name": "SYN St Petersburg Warsaw Station"
    },
    {
      "city": "SYN_C_WIR",
      "country": "RU",
      "frontier": true,
      "frontierPair": "SYN_EYD",
      "id": "SYN_WIR",
      "name": "SYN Wirballen"
    }
  ],
  "stops": {
    "arr": [
      -1,
      38700,
      -1,
      54300,
      -1,
      66600,
      -1,
      75000,
      -1,
      29700,
      64500,
      70500,
      -1,
      17400,
      48000,
      53700,
      -1,
      42300,
      78000,
      49500,
      -1,
      48600,
      53700,
      22200,
      -1,
      40800,
      -1,
      39000,
      -1,
      54600,
      -1,
      66600,
      -1,
      75600
    ],
    "arrDay": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      0,
      1,
      1,
      1,
      0,
      0,
      0,
      1,
      0,
      1,
      0,
      1,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "cite": [
      4,
      4,
      4,
      4,
      7,
      7,
      7,
      7,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      8,
      8,
      8,
      8,
      6,
      6,
      6,
      6,
      9,
      9,
      10,
      10,
      10,
      10,
      11,
      11,
      11,
      11
    ],
    "dep": [
      32400,
      -1,
      40500,
      -1,
      52200,
      -1,
      68400,
      -1,
      57600,
      31200,
      66000,
      -1,
      46800,
      18300,
      49200,
      -1,
      45000,
      44100,
      79200,
      -1,
      75600,
      -1,
      56400,
      -1,
      68400,
      -1,
      32400,
      -1,
      40500,
      -1,
      52200,
      -1,
      69000,
      -1
    ],
    "depDay": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      0,
      1,
      1,
      1,
      0,
      0,
      0,
      1,
      0,
      1,
      0,
      1,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "flags": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      3,
      3,
      0,
      0,
      3,
      3,
      3,
      3,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "station": [
      3,
      1,
      1,
      4,
      4,
      1,
      1,
      3,
      4,
      0,
      2,
      6,
      4,
      0,
      2,
      6,
      6,
      2,
      0,
      4,
      6,
      5,
      6,
      5,
      5,
      6,
      3,
      1,
      1,
      4,
      4,
      1,
      1,
      3
    ]
  },
  "throughLinks": [
    {
      "cite": 5,
      "classMask": 1,
      "fromTrip": "SYN_E1.SYN_T2.c1",
      "station": "SYN_WIR",
      "toTrip": "SYN_E1.SYN_T3.c1"
    }
  ],
  "transfers": [
    {
      "basis": "historical",
      "cite": 5,
      "from": "SYN_EYD",
      "kind": "frontier-change",
      "minSec": 3600,
      "to": "SYN_WIR"
    },
    {
      "basis": "historical",
      "cite": 8,
      "from": "SYN_WIR",
      "kind": "frontier-change",
      "minSec": 3600,
      "to": "SYN_EYD"
    }
  ],
  "trips": [
    {
      "cite": 4,
      "classMask": 7,
      "edition": "SYN_E1",
      "firstStop": 0,
      "id": "SYN_E1.SYN_T1.c0",
      "mode": "rail",
      "nStops": 2,
      "name": null,
      "operator": "SYN-SECR",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            127
          ]
        ]
      },
      "sleeper": false,
      "trainKey": "SYN-SECR-11",
      "trainNo": "11",
      "truth": [
        [
          5233,
          5355
        ]
      ]
    },
    {
      "cite": 4,
      "classMask": 3,
      "edition": "SYN_E1",
      "firstStop": 2,
      "id": "SYN_E1.SYN_T1.c1",
      "mode": "steamer",
      "nStops": 2,
      "name": null,
      "operator": "SYN-BSM",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            127
          ]
        ]
      },
      "sleeper": false,
      "trainKey": "SYN-BSM-21",
      "trainNo": "21",
      "truth": [
        [
          5233,
          5355
        ]
      ]
    },
    {
      "cite": 7,
      "classMask": 3,
      "edition": "SYN_E1",
      "firstStop": 4,
      "id": "SYN_E1.SYN_T1U.c0",
      "mode": "steamer",
      "nStops": 2,
      "name": null,
      "operator": "SYN-BSM",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            127
          ]
        ]
      },
      "sleeper": false,
      "trainKey": "SYN-BSM-22",
      "trainNo": "22",
      "truth": [
        [
          5233,
          5355
        ]
      ]
    },
    {
      "cite": 7,
      "classMask": 7,
      "edition": "SYN_E1",
      "firstStop": 6,
      "id": "SYN_E1.SYN_T1U.c1",
      "mode": "rail",
      "nStops": 2,
      "name": null,
      "operator": "SYN-SECR",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            127
          ]
        ]
      },
      "sleeper": false,
      "trainKey": "SYN-SECR-12",
      "trainNo": "12",
      "truth": [
        [
          5233,
          5355
        ]
      ]
    },
    {
      "cite": 5,
      "classMask": 7,
      "edition": "SYN_E1",
      "firstStop": 8,
      "id": "SYN_E1.SYN_T2.c0",
      "mode": "rail",
      "nStops": 4,
      "name": null,
      "operator": "SYN-KPEV",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            127
          ]
        ]
      },
      "sleeper": false,
      "trainKey": "SYN-KPEV-D1",
      "trainNo": "D 1",
      "truth": [
        [
          5233,
          5355
        ]
      ]
    },
    {
      "cite": 5,
      "classMask": 1,
      "edition": "SYN_E1",
      "firstStop": 12,
      "id": "SYN_E1.SYN_T2.c1",
      "mode": "rail",
      "nStops": 4,
      "name": "SYN Nord-Express",
      "operator": "SYN-CIWL",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            9
          ]
        ]
      },
      "sleeper": true,
      "trainKey": "SYN-NORD",
      "trainNo": "N 1",
      "truth": [
        [
          5233,
          5355
        ]
      ]
    },
    {
      "cite": 8,
      "classMask": 7,
      "edition": "SYN_E1",
      "firstStop": 16,
      "id": "SYN_E1.SYN_T2U.c0",
      "mode": "rail",
      "nStops": 4,
      "name": null,
      "operator": "SYN-KPEV",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            127
          ]
        ]
      },
      "sleeper": false,
      "trainKey": "SYN-KPEV-D2",
      "trainNo": "D 2",
      "truth": [
        [
          5233,
          5355
        ]
      ]
    },
    {
      "cite": 6,
      "classMask": 7,
      "edition": "SYN_E1",
      "firstStop": 20,
      "id": "SYN_E1.SYN_T3.c0",
      "mode": "rail",
      "nStops": 2,
      "name": null,
      "operator": "SYN-RUS",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            127
          ]
        ]
      },
      "sleeper": true,
      "trainKey": "SYN-RUS-3",
      "trainNo": "3",
      "truth": [
        [
          5233,
          5355
        ]
      ]
    },
    {
      "cite": 6,
      "classMask": 1,
      "edition": "SYN_E1",
      "firstStop": 22,
      "id": "SYN_E1.SYN_T3.c1",
      "mode": "rail",
      "nStops": 2,
      "name": "SYN Nord-Express",
      "operator": "SYN-CIWL",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            18
          ]
        ]
      },
      "sleeper": true,
      "trainKey": "SYN-NORD",
      "trainNo": "N 1",
      "truth": [
        [
          5233,
          5355
        ]
      ]
    },
    {
      "cite": 9,
      "classMask": 7,
      "edition": "SYN_E1",
      "firstStop": 24,
      "id": "SYN_E1.SYN_T3U.c0",
      "mode": "rail",
      "nStops": 2,
      "name": null,
      "operator": "SYN-RUS",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            127
          ]
        ]
      },
      "sleeper": true,
      "trainKey": "SYN-RUS-4",
      "trainNo": "4",
      "truth": [
        [
          5233,
          5355
        ]
      ]
    },
    {
      "cite": 10,
      "classMask": 7,
      "edition": "SYN_E2",
      "firstStop": 26,
      "id": "SYN_E2.SYN_T1.c0",
      "mode": "rail",
      "nStops": 2,
      "name": null,
      "operator": "SYN-SECR",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            127
          ]
        ]
      },
      "sleeper": false,
      "trainKey": "SYN-SECR-11",
      "trainNo": "11",
      "truth": [
        [
          5222,
          5232
        ]
      ]
    },
    {
      "cite": 10,
      "classMask": 3,
      "edition": "SYN_E2",
      "firstStop": 28,
      "id": "SYN_E2.SYN_T1.c1",
      "mode": "steamer",
      "nStops": 2,
      "name": null,
      "operator": "SYN-BSM",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            63
          ]
        ]
      },
      "sleeper": false,
      "trainKey": "SYN-BSM-21",
      "trainNo": "21",
      "truth": [
        [
          5222,
          5232
        ]
      ]
    },
    {
      "cite": 11,
      "classMask": 3,
      "edition": "SYN_E2",
      "firstStop": 30,
      "id": "SYN_E2.SYN_T1U.c0",
      "mode": "steamer",
      "nStops": 2,
      "name": null,
      "operator": "SYN-BSM",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            127
          ]
        ]
      },
      "sleeper": false,
      "trainKey": "SYN-BSM-22",
      "trainNo": "22",
      "truth": [
        [
          5222,
          5232
        ]
      ]
    },
    {
      "cite": 11,
      "classMask": 7,
      "edition": "SYN_E2",
      "firstStop": 32,
      "id": "SYN_E2.SYN_T1U.c1",
      "mode": "rail",
      "nStops": 2,
      "name": null,
      "operator": "SYN-SECR",
      "run": {
        "also": [],
        "except": [],
        "ranges": [
          [
            5222,
            5355,
            127
          ]
        ]
      },
      "sleeper": false,
      "trainKey": "SYN-SECR-14",
      "trainNo": "14",
      "truth": [
        [
          5222,
          5232
        ]
      ]
    }
  ],
  "zones": [
    {
      "appliesTo": "railway",
      "cite": 0,
      "from": -7091,
      "id": "SYN_Z_GMT",
      "name": "SYN Greenwich railway time",
      "offsetSec": 0,
      "to": null
    },
    {
      "appliesTo": "civil",
      "cite": 0,
      "from": -7091,
      "id": "SYN_Z_GMT_CIV",
      "name": "SYN Greenwich civil time",
      "offsetSec": 0,
      "to": null
    },
    {
      "appliesTo": "railway",
      "cite": 0,
      "from": -2466,
      "id": "SYN_Z_MEZ",
      "name": "SYN Central European railway time",
      "offsetSec": 3600,
      "to": null
    },
    {
      "appliesTo": "civil",
      "cite": 0,
      "from": -2466,
      "id": "SYN_Z_MEZ_CIV",
      "name": "SYN Central European civil time",
      "offsetSec": 3600,
      "to": null
    },
    {
      "appliesTo": "railway",
      "cite": 0,
      "from": -7305,
      "id": "SYN_Z_SPB",
      "name": "SYN Petersburg railway time",
      "offsetSec": 7278,
      "to": null
    },
    {
      "appliesTo": "civil",
      "cite": 0,
      "from": -7305,
      "id": "SYN_Z_SPB_CIV",
      "name": "SYN Petersburg civil time",
      "offsetSec": 7278,
      "to": null
    }
  ]
} satisfies ReadyBundle;
