/**
 * Compiles the synthetic world (tools/schema/test/fixtures/syn-world) with the manifest
 * fixtures/syn-c07.data-manifest.json and checks the result against the kit contract three ways:
 * structurally (shape.ts), by type (fixtures/syn-c07.bundle.ts declares the expected bundle with
 * `satisfies ReadyBundle`, so tsc checks it), and by equality with that typed fixture.
 * Regenerate the fixture after an intended change with UPDATE_GOLDEN=1 npx vitest run tools/compile.
 */
import { describe, it, expect } from 'vitest';
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { canonicalJson } from '#kit/sim/canonical.ts';
import { dayFromIso } from '#kit/time/calendar.ts';
import { runsOn } from '#kit/timetable/model.ts';
import { cloneRawDataset, loadRaw, parseDataset, type RawDataset } from '../../schema/dataset.ts';
import { CompileError, compileBundle, parseManifest, type Manifest } from '../compile-bundles.ts';
import { checkBundleShape } from '../shape.ts';
import { SYN_C07_BUNDLE } from './fixtures/syn-c07.bundle.ts';

const WORLD = fileURLToPath(new URL('../../schema/test/fixtures/syn-world', import.meta.url));
const MANIFEST = fileURLToPath(new URL('./fixtures/syn-c07.data-manifest.json', import.meta.url));
const GOLDEN = fileURLToPath(new URL('./fixtures/syn-c07.bundle.ts', import.meta.url));
const ROOT = fileURLToPath(new URL('../../..', import.meta.url));

let base: RawDataset | null = null;
const world = () => { base ??= loadRaw(WORLD); return cloneRawDataset(base); };
const manifest = (patch: Partial<Manifest> = {}): Manifest => ({ ...parseManifest(readFileSync(MANIFEST, 'utf8')), ...patch });
const compile = (raw = world(), m = manifest(), opts = { synthetic: true }) => compileBundle(parseDataset(raw), m, opts);
const refusal = (f: () => unknown): string => {
  try { f(); } catch (e) { if (e instanceof CompileError) return e.reasons.join('\n'); throw e; }
  return '(compiled)';
};
const d = dayFromIso;

describe('compile-bundles: the synthetic world', () => {
  const { bundle, json } = compile();

  it('satisfies the kit contract structurally', () => {
    expect(checkBundleShape(JSON.parse(json))).toEqual([]);
  });
  it('equals the typed fixture (checked against ReadyBundle by tsc)', () => {
    if (process.env.UPDATE_GOLDEN === '1' || !existsSync(GOLDEN)) {
      writeFileSync(GOLDEN, `/* Generated by tools/compile/test/compile.test.ts (UPDATE_GOLDEN=1). Do not edit. */\nimport type { ReadyBundle } from '#kit/data/bundle.ts';\n\nexport const SYN_C07_BUNDLE = ${JSON.stringify(JSON.parse(json), null, 2)} satisfies ReadyBundle;\n`);
    }
    expect(JSON.parse(json)).toEqual(SYN_C07_BUNDLE);
  });
  it('is byte-identical across independent runs, with a hash of the body', () => {
    const again = compileBundle(parseDataset(loadRaw(WORLD)), manifest(), { synthetic: true }).json;
    expect(again).toBe(json);
    const { meta, ...body } = JSON.parse(json) as typeof bundle;
    expect(meta.dataHash).toBe(createHash('sha256').update(canonicalJson(body)).digest('hex').slice(0, 16));
    expect(json).toBe(`${canonicalJson(JSON.parse(json))}\n`);
  });
  it('sets meta from the manifest', () => {
    expect(bundle.meta).toEqual({ game: 'syn-c07', status: 'ready', synthetic: true, dataHash: bundle.meta.dataHash, freezeTag: 'syn-data-v1', schema: 1, window: [d('1914-04-20'), d('1914-08-31')] });
  });
  it('selects trips of the listed editions only, sorted, with their stops', () => {
    expect(bundle.trips.map((t) => t.id)).toEqual([
      'SYN_E1.SYN_T1.c0', 'SYN_E1.SYN_T1.c1', 'SYN_E1.SYN_T1U.c0', 'SYN_E1.SYN_T1U.c1', 'SYN_E1.SYN_T2.c0', 'SYN_E1.SYN_T2.c1', 'SYN_E1.SYN_T2U.c0',
      'SYN_E1.SYN_T3.c0', 'SYN_E1.SYN_T3.c1', 'SYN_E1.SYN_T3U.c0', 'SYN_E2.SYN_T1.c0', 'SYN_E2.SYN_T1.c1', 'SYN_E2.SYN_T1U.c0', 'SYN_E2.SYN_T1U.c1',
    ]);
    const t = bundle.trips.find((x) => x.id === 'SYN_E1.SYN_T2.c0')!;
    const st = (k: number) => bundle.stations[bundle.stops.station[t.firstStop + k]!]!.id;
    expect([0, 1, 2, 3].map(st)).toEqual(['SYN_OST', 'SYN_BER', 'SYN_EYD', 'SYN_WIR']);
    expect(bundle.stops.dep[t.firstStop]).toBe(16 * 3600);
    expect(bundle.stops.arr[t.firstStop]).toBe(-1);
    expect(bundle.stops.arrDay[t.firstStop + 3]).toBe(1);
    expect(bundle.stops.flags[t.firstStop + 2]).toBe(1 | 2);
    expect(t.classMask).toBe(7);
  });
  it('compiles the printed rule over the bundle window and truth over the edition validity', () => {
    const winter = bundle.trips.find((x) => x.id === 'SYN_E2.SYN_T1.c1')!; // except Sundays, valid to 30 April
    const summer = bundle.trips.find((x) => x.id === 'SYN_E1.SYN_T1.c1')!;
    expect(winter.truth).toEqual([[d('1914-04-20'), d('1914-04-30')]]);
    expect(summer.truth).toEqual([[d('1914-05-01'), d('1914-08-31')]]);
    // A player holding the winter guide in June still reads "daily except Sundays".
    expect(runsOn(winter.run, d('1914-06-01'))).toBe(true);
    expect(runsOn(winter.run, d('1914-06-07'))).toBe(false);
    // On the ground, only the summer service runs then.
    const truthRuns = (t: typeof winter, day: number) => t.truth.some(([a, b]) => day >= a && day <= b) && runsOn(t.run, day);
    expect(truthRuns(winter, d('1914-06-01'))).toBe(false);
    expect(truthRuns(summer, d('1914-06-01'))).toBe(true);
    expect(truthRuns(winter, d('1914-04-27'))).toBe(true);
    const nord = bundle.trips.find((x) => x.id === 'SYN_E1.SYN_T2.c1')!;
    expect(nord.run.ranges).toEqual([[d('1914-04-20'), d('1914-08-31'), 0b1001]]);
  });
  it('builds a deduplicated, sorted citation table with page details', () => {
    const keys = bundle.citations.map((c) => `${c.source}:${c.pageSeq}:${c.tableRef ?? '-'}`);
    expect(keys).toEqual([...new Set(keys)]);
    expect(keys).toEqual([...keys].sort());
    const t = bundle.trips.find((x) => x.id === 'SYN_E1.SYN_T2.c0')!;
    expect(bundle.citations[t.cite]).toEqual({ source: 'SYN_SRC_S', sourceTitle: 'SYN Continental Guide, June 1914', edition: 'SYN_E1', pageSeq: 11, printedPage: '11', tableRef: 'SYN_T2' });
    expect(bundle.citations.find((c) => c.source === 'SYN_SRC_H')!.edition).toBeNull();
  });
  it('includes params named in the manifest, effects of included events, and converts to exclusive ends', () => {
    expect(bundle.params.map((p) => p.id)).toEqual(['SYN_P002', 'SYN_P003', 'SYN_P004', 'SYN_P005']);
    expect(bundle.params.find((p) => p.id === 'SYN_P005')!.to).toBe(d('1915-01-01'));
    expect(bundle.params.find((p) => p.id === 'SYN_P004')).toMatchObject({ dv: 'DV-002', valueBasis: 'design', tier: 2 });
    expect(bundle.calendar.map((e) => [e.id, e.day, e.timeLocal])).toEqual([['SYN_EV2', d('1914-07-29'), null], ['SYN_EV1', d('1914-08-01'), 19 * 3600]]);
    expect(bundle.designValues.map((v) => v.id)).toEqual(['DV-001', 'DV-002', 'DV-003']);
    expect(bundle.minChange.find((m) => m.station === 'SYN_DOV')).toEqual({ station: 'SYN_DOV', minSec: 1200, basis: 'design', dv: 'DV-001' });
  });
  it('includes zones and station zones with odd-second offsets', () => {
    expect(bundle.zones.find((z) => z.id === 'SYN_Z_SPB')!.offsetSec).toBe(7278);
    expect(bundle.stationZones.map((z) => z.station)).toEqual(bundle.stations.map((s) => s.id));
  });
});

describe('compile-bundles: refusals', () => {
  it('refuses synthetic sources without --synthetic', () => {
    expect(refusal(() => compile(world(), manifest(), { synthetic: false }))).toMatch(/synthetic sources \(SYN_SRC_S, .*\) need --synthetic/);
  });
  it('refuses any validation error', () => {
    const raw = world();
    raw.tables.stops.rows.find((r) => r.values.service_id === 'SYN_E1.SYN_T2.c0' && r.values.seq === '2')!.values.arr_dayoff = '0';
    expect(refusal(() => compile(raw))).toMatch(/validation error\(s\); run tools\/validate\/run.ts\. First: V03 error service SYN_E1.SYN_T2.c0: time goes backwards/);
  });
  it('refuses unresolved stops and design rows without design-value ids (even with validation off)', () => {
    const raw = world();
    raw.tables.stops.rows.find((r) => r.values.service_id === 'SYN_E1.SYN_T1.c0' && r.values.seq === '2')!.values.status = 'illegible';
    raw.tables.min_change.rows.find((r) => r.values.station_id === 'SYN_BER')!.values.src_or_dv = 'SYN_SRC_S:p11:SYN_T2:-:-';
    raw.tables.params.rows.find((r) => r.values.row_id === 'SYN_P004')!.values.dv_id = '';
    const why = refusal(() => compileBundle(parseDataset(raw), manifest(), { synthetic: true, validate: false }));
    expect(why).toMatch(/stop SYN_E1.SYN_T1.c0 seq 2 has status illegible/);
    expect(why).toMatch(/min change SYN_BER: design row without a design-value id/);
    expect(why).toMatch(/param SYN_P004: design-basis row without a dv_id/);
  });
  it('refuses a manifest that is not ready or names unknown rows', () => {
    expect(refusal(() => compile(world(), manifest({ status: 'awaiting-data' })))).toMatch(/status is "awaiting-data"/);
    const why = refusal(() => compile(world(), manifest({ segments: ['SYN_S_XX'], editions: ['SYN_E7'], params: ['no_such_param'] })));
    expect(why).toMatch(/segment SYN_S_XX is not in segments.csv/);
    expect(why).toMatch(/edition SYN_E7 is not in editions.csv/);
    const m = manifest({ calendarWindow: null });
    delete m.window;
    expect(refusal(() => compile(world(), m))).toMatch(/neither window nor calendarWindow/);
  });
});

describe('compile-bundles.ts command line', () => {
  const cli = (...a: string[]) => spawnSync(process.execPath, ['tools/compile/compile-bundles.ts', ...a], { cwd: ROOT, encoding: 'utf8' });
  it('writes <out>/<game>.bundle.json with --synthetic and refuses without it', () => {
    const out = mkdtempSync(join(tmpdir(), 'syn-compile-'));
    const no = cli('--manifest', MANIFEST, '--data', WORLD, '--out', out);
    expect(no.status).toBe(1);
    expect(no.stderr).toMatch(/need --synthetic/);
    expect(existsSync(join(out, 'syn-c07.bundle.json'))).toBe(false);
    const yes = cli('--manifest', MANIFEST, '--data', WORLD, '--out', out, '--synthetic');
    expect(yes.status, yes.stderr).toBe(0);
    expect(readFileSync(join(out, 'syn-c07.bundle.json'), 'utf8')).toBe(compile().json);
  });
  it('--all skips games still awaiting data', () => {
    const out = mkdtempSync(join(tmpdir(), 'syn-compile-'));
    const r = cli('--all', '--out', out);
    expect(r.status, r.stderr).toBe(0);
    for (const line of r.stdout.trim().split('\n')) expect(line).toMatch(/^(skipped .*: manifest status is awaiting-data|wrote .*)$/);
  });
});
