// Writes the generated indexes: every file in src/data/stories, src/data/ops and src/art/vignettes is imported.
// Run by test/validate.mjs and build.mjs, so a new file is picked up without editing anything else.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const HEAD = '// Generated by tools/indexes.mjs. Do not edit: add or remove files in this folder instead.\n';

function list(dir) {
  return fs.readdirSync(dir).filter((f) => f.endsWith('.js') && f !== 'index.js').sort();
}
function write(file, text) { // atomic, so parallel runs never see half a file
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === text) return;
  const tmp = `${file}.${process.pid}.tmp`;
  fs.writeFileSync(tmp, text);
  fs.renameSync(tmp, file);
}

export function writeIndexes() {
  const stories = list(path.join(ROOT, 'src/data/stories'));
  write(path.join(ROOT, 'src/data/stories/index.js'), HEAD + stories.map((f, i) => `import s${i} from './${f}';\n`).join('')
    + `\nexport const FILES = ${JSON.stringify(stories)};\nexport default [${stories.map((_, i) => `...s${i}`).join(', ')}];\n`);
  const ops = list(path.join(ROOT, 'src/data/ops'));
  write(path.join(ROOT, 'src/data/ops/index.js'), HEAD + ops.map((f, i) => `import o${i} from './${f}';\n`).join('')
    + `\nexport default [${ops.map((_, i) => `o${i}`).join(', ')}];\n`);
  const vig = list(path.join(ROOT, 'src/art/vignettes'));
  write(path.join(ROOT, 'src/art/vignettes/index.js'), HEAD + vig.map((f, i) => `import v${i} from './${f}';\n`).join('')
    + `\nexport default [${vig.map((_, i) => `v${i}`).join(', ')}];\n`);
  return { stories: stories.length, ops: ops.length, vignettes: vig.length };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) console.log(writeIndexes());
