// Packs the coastlines (land.json, land-lo.json) into compact strings: points on a 0.02° grid, delta-encoded,
// one character per coordinate where the step is small. Writes src/ui/land.pack.js; the globe decodes it at start.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
const Q = 50; // 1/50 degree
function big(n) { // escape 'A' + three characters for any integer in ±131071
  const v = n + 131072;
  return 'A' + A[(v >> 12) & 63] + A[(v >> 6) & 63] + A[v & 63];
}
function pack(geo) {
  return geo.coordinates.map((poly) => poly.map((ring) => {
    let out = '', px = 0, py = 0, first = true;
    for (const [lon, lat] of ring) {
      const x = Math.round(lon * Q), y = Math.round(lat * Q);
      if (first) { out += big(x) + big(y); first = false; }
      else { for (const d of [x - px, y - py]) out += d >= -31 && d <= 31 ? A[d + 32] : big(d); }
      px = x; py = y;
    }
    return out;
  }).join('|')).join('~');
}
const hi = pack(JSON.parse(fs.readFileSync(path.join(ROOT, 'land.json'), 'utf8')));
const lo = pack(JSON.parse(fs.readFileSync(path.join(ROOT, 'land-lo.json'), 'utf8')));
fs.writeFileSync(path.join(ROOT, 'src/ui/land.pack.js'), `// Generated by tools/pack-land.mjs from land.json and land-lo.json (Natural Earth via world-atlas). Do not edit.\nexport const HI = '${hi}';\nexport const LO = '${lo}';\n`);
console.log(`packed: hi ${(hi.length / 1024).toFixed(0)} KB, lo ${(lo.length / 1024).toFixed(0)} KB`);
