// Generated by tools/indexes.mjs. Do not edit: add or remove files in this folder instead.
import v0 from './AMS.js';
import v1 from './ATH.js';
import v2 from './BAR.js';
import v3 from './BEG.js';
import v4 from './BRU.js';
import v5 from './BUC.js';
import v6 from './BUD.js';
import v7 from './COL.js';
import v8 from './FLU.js';
import v9 from './HAM.js';
import v10 from './IST.js';
import v11 from './LON.js';
import v12 from './MAD.js';
import v13 from './MAR.js';
import v14 from './MUN.js';
import v15 from './ODE.js';
import v16 from './PAR.js';
import v17 from './PRG.js';
import v18 from './SAR.js';
import v19 from './TRI.js';
import v20 from './VEN.js';
import v21 from './VIE.js';
import v22 from './WAR.js';
import v23 from './ZUR.js';

export default [v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23];
