/**
 * Coverage matrix.
 *
 *   node tools/discover/coverage.ts [--segments seg1,seg2,…] [--tier-a seg1,…] [--check]
 *
 * Reads data/sources/coverage.csv (edition_id, segment_id, status, pages, table_refs, notes; status is
 * full | partial | missing | restricted) and writes data/sources/COVERAGE.md: an edition × segment
 * matrix whose cells give the status, pages and table references, a per-edition summary and the
 * notes. --segments fixes the column order (others follow, sorted); --tier-a adds the share of tier-A
 * segments in full view per edition (gate G1 asks for at least 90%). --check exits 1 if COVERAGE.md
 * is out of date instead of writing it.
 */
import { existsSync, readFileSync } from 'node:fs';
import { cmpStr, readCsvFileOr, writeTextFile } from '../keying/csv.ts';
import { coverageCsv, coverageMd, roots } from '../keying/paths.ts';

export const COVERAGE_COLUMNS = ['edition_id', 'segment_id', 'status', 'pages', 'table_refs', 'notes'] as const;
export const STATUSES = ['full', 'partial', 'missing', 'restricted'] as const;
export type CoverageStatus = (typeof STATUSES)[number];

export interface CoverageRow { edition_id: string; segment_id: string; status: CoverageStatus; pages: string; table_refs: string; notes: string }

const SYMBOL: Record<CoverageStatus, string> = { full: '● full', partial: '◐ partial', missing: '○ missing', restricted: '⊘ restricted' };

export function parseCoverage(rows: ReadonlyArray<Record<string, string>>): { rows: CoverageRow[]; errors: string[] } {
  const errors: string[] = [];
  const out: CoverageRow[] = [];
  const seen = new Set<string>();
  rows.forEach((r, i) => {
    const where = `coverage.csv row ${i + 2}`;
    const e = (r.edition_id ?? '').trim(); const s = (r.segment_id ?? '').trim(); const st = (r.status ?? '').trim();
    if (!e || !s) { errors.push(`${where}: edition_id and segment_id are required`); return; }
    if (!(STATUSES as readonly string[]).includes(st)) { errors.push(`${where}: status "${st}" is not one of ${STATUSES.join('|')}`); return; }
    const k = `${e}\u0000${s}`;
    if (seen.has(k)) { errors.push(`${where}: duplicate ${e} × ${s}`); return; }
    seen.add(k);
    out.push({ edition_id: e, segment_id: s, status: st as CoverageStatus, pages: (r.pages ?? '').trim(), table_refs: (r.table_refs ?? '').trim(), notes: (r.notes ?? '').trim() });
  });
  return { rows: out, errors };
}

const esc = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

function cell(r: CoverageRow | undefined): string {
  if (!r) return '·';
  const parts = [SYMBOL[r.status]];
  if (r.pages) parts.push(`pp. ${r.pages}`);
  if (r.table_refs) parts.push(`T ${r.table_refs}`);
  return esc(parts.join('<br>'));
}

export function renderCoverage(rows: readonly CoverageRow[], o: { segments?: readonly string[]; tierA?: readonly string[] } = {}): string {
  const editions = [...new Set(rows.map((r) => r.edition_id))].sort(cmpStr);
  const listed = (o.segments ?? []).filter(Boolean);
  const rest = [...new Set(rows.map((r) => r.segment_id))].filter((s) => !listed.includes(s)).sort(cmpStr);
  const segments = [...listed, ...rest];
  const at = new Map(rows.map((r) => [`${r.edition_id}\u0000${r.segment_id}`, r]));
  const L: string[] = [];
  L.push('# Source coverage');
  L.push('');
  L.push('Generated by `node tools/discover/coverage.ts` from `data/sources/coverage.csv`; do not edit by hand.');
  L.push('');
  L.push('Legend: ● full (in full view, every needed train) · ◐ partial · ○ missing · ⊘ restricted (exists, not in full view here) · `·` not assessed. `pp.` are printed pages or page_seq as recorded; `T` are table references.');
  L.push('');
  if (rows.length === 0) { L.push('_No coverage rows yet._'); L.push(''); return L.join('\n'); }
  L.push('## Matrix');
  L.push('');
  L.push(`| Edition | ${segments.map(esc).join(' | ')} |`);
  L.push(`|---|${segments.map(() => '---').join('|')}|`);
  for (const e of editions) L.push(`| ${esc(e)} | ${segments.map((s) => cell(at.get(`${e}\u0000${s}`))).join(' | ')} |`);
  L.push('');
  L.push('## Summary per edition');
  L.push('');
  const tierA = (o.tierA ?? []).filter(Boolean);
  L.push(`| Edition | full | partial | missing | restricted | not assessed${tierA.length ? ' | tier A in full view' : ''} |`);
  L.push(`|---|---|---|---|---|---${tierA.length ? '|---' : ''}|`);
  for (const e of editions) {
    const mine = rows.filter((r) => r.edition_id === e);
    const n = (st: CoverageStatus) => mine.filter((r) => r.status === st).length;
    let line = `| ${esc(e)} | ${n('full')} | ${n('partial')} | ${n('missing')} | ${n('restricted')} | ${segments.length - mine.length}`;
    if (tierA.length) {
      const full = tierA.filter((s) => at.get(`${e}\u0000${s}`)?.status === 'full').length;
      const pct = Math.floor((full * 1000) / tierA.length) / 10;
      line += ` | ${full}/${tierA.length} (${pct}%)${pct >= 90 ? ' ✓ G1' : ''}`;
    }
    L.push(`${line} |`);
  }
  const noted = rows.filter((r) => r.notes).sort((a, b) => cmpStr(a.edition_id, b.edition_id) || cmpStr(a.segment_id, b.segment_id));
  if (noted.length) {
    L.push('');
    L.push('## Notes');
    L.push('');
    for (const r of noted) L.push(`- **${r.edition_id} × ${r.segment_id}** (${r.status}): ${r.notes}`);
  }
  L.push('');
  return L.join('\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const opt = (f: string) => { const i = args.indexOf(f); return i >= 0 ? args[i + 1] : undefined; };
  const r = roots();
  const t = readCsvFileOr(coverageCsv(r), COVERAGE_COLUMNS);
  const parsed = parseCoverage(t.rows);
  for (const e of parsed.errors) console.error(e);
  if (parsed.errors.length) process.exit(1);
  const md = renderCoverage(parsed.rows, { segments: opt('--segments')?.split(',') ?? [], tierA: opt('--tier-a')?.split(',') ?? [] });
  const out = coverageMd(r);
  if (args.includes('--check')) {
    const cur = existsSync(out) ? readFileSync(out, 'utf8') : '';
    if (cur !== md) { console.error(`${out} is out of date; run node tools/discover/coverage.ts`); process.exit(1); }
    console.log('coverage: up to date');
  } else {
    writeTextFile(out, md);
    console.log(`${out}: ${parsed.rows.length} row(s)`);
  }
}
